### ISSUE TITLE
gsl installation issue

### ISSUE THREAD

**Issue by rgoalcast** [ampl/gsl#25]
I am trying for gsl-2.4 installation by following steps

```
cd gsl-2.4
./configure
make
make install 
```

Making install in gsl
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in utils
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in sys
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/include/gsl'
mkdir: /usr/local/include: Permission denied
mkdir: /usr/local/include: No such file or directory
make[2]: *** [install-pkgincludeHEADERS] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

Still not able to install, what will be next step?

**Comment by fdabrandao** [comment]
This project provides CMake build support for the GSL library, which is an alternative to the default Autotools build support that you are using. Nevertheless, that problem seems to be simply a missing `sudo` before `make install`, since `make install` will copy the generated files to locations that may require root access.
